config/routes.rb
Rails.application.routes.draw do
  resources :features
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feature.rb
class Feature < ApplicationRecord
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@projects = Project.all
	end

	def show
		@project = Project.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myprocess</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<h1><%= pluralize(@projects.count, 'Project') %></h1>
<% @projects.each do |project| %>
	<article>
		<header>
			<h2><%= link_to(project.proj_name, project) %></h2>
		</header>
		<p>
			<%= project.description %>
		</p>
		<table>
		<tr>
			<th>Client: </th>
			<td><%= project.client %></td>
		</tr>
		<tr>
			<th>Status: </th>
			<td><%= project.status%></td>
		</tr>
		</table>
	</article>
<% end %>

app/views/projects/show.html.erb
<h1><%= @project.proj_name %></h1>
	<article>
		<p>
			<%= @project.description %>
		</p>
		<table>
		<tr>
			<th>Client:</th>
			<td><%= @project.client %></td>
		</tr>
		<tr>
			<th>Status:</th>
			<td><%= @project.status %></td>
		</tr>
		</table>
	</article>


<%= link_to "All Projects", projects_path %>
<%= link_to "Edit", edit_project_path(@project) %>
<%= link_to "Delete", project_path(@project), method: :delete, 
	data: {confirm: 'Are you sure?'} %>